language: java
sudo: required
dist: bionic
os:
 - linux

env:
 global:
  - TSK_HOME=$TRAVIS_BUILD_DIR/sleuthkit/sleuthkit

addons:
  apt:
    update: true
    packages:
    - libafflib-dev
    - libewf-dev
    - libpq-dev
    - autopoint
    - libsqlite3-dev
    - ant
    - libcppunit-dev
    - wget
    - openjdk-8-jdk
    - openjfx=8u161-b12-1ubuntu2
    - libopenjfx-java=8u161-b12-1ubuntu2
    - libopenjfx-jni=8u161-b12-1ubuntu2
  homebrew:
    update: true
    packages:
    - ant
    - libewf
    - gettext
    - cppunit
    - afflib

python:
  - "2.7"

before_install:
 - git clone https://github.com/sleuthkit/sleuthkit.git sleuthkit/sleuthkit
 - python setupSleuthkitBranch.py

install:
 - sudo apt-get install testdisk
 - cd sleuthkit/sleuthkit
 - ./travis_install_libs.sh

script:
 - set -e
 - echo "Building TSK..."
 - ./bootstrap && ./configure --prefix=/usr && make
 - pushd bindings/java/ && ant -q dist-PostgreSQL && popd
 - echo "Building Autopsy..." && echo -en 'travis_fold:start:script.build\\r'
 - cd $TRAVIS_BUILD_DIR/
 - ant build
 - echo -en 'travis_fold:end:script.build\\r'
 - echo "Testing Autopsy..." && echo -en 'travis_fold:start:script.tests\\r'
 - cd Core/
 - ant -q getTestDataFiles
 - echo "Free Space:"
 - echo `df -h .` 
 - xvfb-run ant -q test
 - echo -en 'travis_fold:end:script.tests\\r'
